---
# defaults file for NTP

ntp_enabled: true 
ntp_timezone: Etc/UTC 
ntp_manage_config: false 
ntp_servers: 
  - 0.pool.ntp.org iburst 
  - 1.pool.ntp.org iburst 
  - 2.pool.ntp.org iburst 
  - 3.pool.ntp.org iburst 

# defaults file for SON
pop: alabs
proj: demo
distro: xenial

