# CENTOS 7
- name: install EPEL
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: install missing modules
  yum: name="perl(Text::CSV_XS)" state=present update_cache=y

- name: install OTRS 
  yum: name=otrs-5.0.12 state=present update_cache=yes

- name: restart Apache
  service: name=httpd state=restarted enabled=yes
