# UBUNTU 16.04
- name: Perl modules manual install (do not use Debian/Ubuntu packages)
  apt: name={{ item }} state=present
  with_items:
  - libapache2-mod-perl2
  - libdbd-mysql-perl
  - libtimedate-perl
  - libnet-dns-perl
  - libnet-ldap-perl
  - libio-socket-ssl-perl
  - libpdf-api2-perl
  - libdbd-mysql-perl
  - libsoap-lite-perl
  - libtext-csv-xs-perl
  - libjson-xs-perl
  - libapache-dbi-perl
  - libxml-libxml-perl
  - libxml-libxslt-perl
  - libyaml-perl
  - libarchive-zip-perl
  - libcrypt-eksblowfish-perl
  - libencode-hanextra-perl
  - libmail-imapclient-perl
  - libtemplate-perl

- name: restart Apache
  service: name=apache2 state=restarted enabled=yes
