version: '2'
services:
  osm-ro-db:
    image: mysql
    container_name: osm-ro-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=osm4u
  osm-ro:
    build:
      context: ../
      dockerfile: docker/Dockerfile-local
    image: osm/ro
    container_name: osm-ro
    restart: always
    environment:
      - RO_DB_ROOT_PASSWORD=osm4u
      - DB_HOST=osm-ro-db
    ports:
      - "9090:9090"
    volumes:
      - /var/log/osm/openmano/logs:/var/log/osm
    depends_on:
      - osm-ro-db
    links:
      - osm-ro-db

