- name: start 2 ids containers
  docker_container:
    name: "snort{{ item }}"
    recreate: yes
    image: glanf/snort # just for PoC - to retrieve private image
    command: sleep 1m
    volumes:
      - /var/log/sonata/snort:/var/log/snort
    log_driver: syslog # gelf
    #log_options:
    #  syslog-address: tcp://my-syslog-server:514
    #  syslog-facility: daemon
  with_sequence: count=2

