---

- name: install tools to manage SELinux on Redhat/CentOS machine
  yum: name={{ item }} state=present
  with_items:
  - libselinux-python
  - libsemanage-python
  - libsemanage-devel
  - policycoreutils-python

- name: ensuring HTTP can reach network ports
  seboolean: name=httpd_can_network_connect state=yes persistent=yes

#- name: checking if SELinux authorizes mongod_port_t to tcp 27017
#  shell: /usr/sbin/semanage port --list | grep "mongod_port_t.*tcp.*"
#  register: selinux_port_check
#  ignore_errors: true

#­ name: adding the port to SELinux managed port if needed
#  shell: semanage port ­a ­t mongod_port_t ­p tcp 27017
#  when: selinux_port_check|failed

- name: SELinux (temporarily) disabled
  selinux: policy=targeted state=permissive

- name: add MongoDB 3.+ repo to YUM
  copy: src=roles/mongo/files/mongodb.repo dest=/etc/yum.repos.d/mongodb.repo owner=root group=root mode=0644

- name: install MongoDB to CentOS7
  yum: name={{ item }} state=present update_cache=yes
  with_items:
  - mongodb-org
  - mongodb-org-server

- name: fix MongoDB to listen at all interfaces
  copy: src=roles/mongo/files/mongod_rpm.conf dest=/etc/mongod.conf owner=root group=root mode=0644

- name: start MongoDB database service
  service: name=mongod state=started enabled=yes
