---

- name: check if an old MongoDB service exists
  stat: path=/etc/init.d/mongod
  register: service_status

# Ubuntu packages installs 'mongodb', 'mongodb-server' and 'mongodb-clients' that conflicts with MongoDB Community Edition, so: remove it first
- name: previously, stop MongoDB service
  service: name=mongod state=stopped enabled=no
  when: service_status.stat.exists
  register: service_stopped

- name: previously, remove MongoDB from system
  apt: name={{ item }} state=absent
  with_items:
  - mongodb
  - mongodb-server
  - mongodb-clients

- name: import the MongoDB public GPG Key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EA312927
    url: https://www.mongodb.org/static/pgp/server-3.2.asc
    state: present
#  shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
#  command: apt-key add install/roles/mongo/files/mongodb-gpg.key

#- name: add a list file for MongoDB 3.+ 
#  copy: src=roles/mongo/files/mongodb_deb.repo dest=/etc/apt/sources.list.d/mongodb-org-3.2.list owner=root group=root mode=0644

- name: "Add MongoDB APT repository in Ubuntu 16.04 LTS"
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"
    state: present
    filename: mongodb-org-3.2
#    update_cache: yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16"

- name: "Add MongoDB APT repository in Ubuntu 14.04 LTS"
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse"
    state: present
#    update_cache: yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"

- name: "Install MongoDB package"
  # 'mongodb-org' is a metapackage that installs 'mongodb-org-server', 'mongodb-org-mongos', 'mongodb-org-shell', 'mongodb-org-tools'
  apt: name=mongodb-org state=present

#- name: fix MongoDB to listen at all interfaces
#  copy: src=roles/mongo/files/mongod_deb.conf dest=/etc/mongod.conf owner=root group=root mode=0644

- name: start MongoDB daemon
  service: name=mongod state=started enabled=yes

