---

- name: MONIT Probe - running Docker containers
  docker_container:
    name: son-monitor-probe
    image: "sonatanfv/son-monitor-probe:{{ sp_ver }}"
    state: started
    restart_policy: "always"
    privileged: yes
    env:
      NODE_NAME: "{{ ansible_hostname }}"
      PROM_SRV: "http://son-monitor-pushgateway:9091/metrics"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/:/rootfs:ro"
      - "/proc:/myhost/proc"
    networks:
      - name: "{{ docker_network_name }}"
