- name: MONIT PROMETHEUS - running Docker containers
  docker_container:
    name: son-monitor-prometheus
    image: "tdierich/son-monitor-prometheus"
    restart_policy: "always"
    state: started
    env:
      RABBIT_URL: "son-broker:5672"
      EMAIL_PASS: "czBuQHRAX21vbl9zeXNfMTY="
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-monitor-prometheus
          - prometheus
    published_ports:
      - "9090:9090"
      - "9089:9089"
      - "8002:8001"

