- name: MONIT Push Gateway - running Docker containers
  docker_container:
    name: son-monitor-pushgateway
    image: "sonatanfv/son-monitor-pushgateway:{{ sp_ver }}"
    restart_policy: "always"
    state: started
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-monitor-pushgateway
          - pushgateway
    published_ports: "9091:9091"
