---
# tasks file for rabbitmq

- include: centos7.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu" 

- name: "To enable RabbitMQ Management Console - port 15672"
  command: rabbitmq-plugins enable rabbitmq_management
