---

- name: UNINSTALLING APACHE
  hosts: "{{ plat }}"
  become: true
  tasks:

  # DEBIAN/UBUNTU
  - name: check if the Apache svc exists
    stat: path=/etc/init.d/apache2
    register: svc_status
    when: ansible_os_family == "Debian"

  - name: stop Apache svc
    service: name=apache2 state=stopped enabled=no
    when: svc_status.stat.exists and ansible_os_family == "Debian"
    #register: svc_stopped

  - name: remove Apache from system
    apt: name={{ item }} state=absent 
    with_items: 
    - apache2
    - apache2-utils
    - apache2-common
    when: ansible_os_family == "Debian"

  # REDHAT/CENTOS
  - name: check if the Apache svc exists
    stat: path=/etc/init.d/httpd
    register: svc_status
    when: ansible_os_family == "RedHat"

  - name: stop Apache svc
    service: name=httpd state=stopped enabled=no
    when: svc_status.stat.exists and ansible_os_family == "RedHat"
    #register: svc_stopped

  - name: remove Apache from system
    apt: name={{ item }} state=absent
    with_items:
    - httpd
    when: ansible_os_family == "RedHat"

