---

- name: remove the Sonata Message Bus (based on RabbitMQ) from the SON SP VM
  hosts: "{{ plat }}"
  become: true
  tasks:

  # Remove the Sonata BROKER Container (if running)
  - name: remove the "SP Message Bus" container
    docker_container:
      name: son-broker
      state: absent

