---
- name: UNINSTALLING Docker 
  hosts: "{{ plat }}"
  become: true
  tasks:

  # UBUNTU

  - name: check if the DOCKER service exists
    stat: path=/etc/init.d/docker
    register: ub14_file_status

  - name: stop DOCKER when running
    service: name=docker state=stopped enabled=no
    when: ub14_file_status.stat.exists
    #register: svc_stopped

#  - name: "Remove Docker APT key"
#    apt_key:
#      keyserver: p80.pool.sks-keyservers.net
#      id: 58118E89F3A912897C070ADBF76221572C52609D
#      state: absent
#     when: ansible_os_family == "Debian"

  - name: "Remove Docker APT repository in Ubuntu 16.04 LTS"
    apt_repository:
      repo: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
      state: absent
    when: ansible_os_family == "Debian" and ansible_distribution_major_version == "16"

  - name: "Remove Docker APT repository in Ubuntu 14.04 LTS"
    apt_repository:
      repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
      state: absent
    when: ansible_os_family == "Debian" and ansible_distribution_major_version == "14"

  - name: "Remove Docker package"
    apt: name=docker-engine state=absent
    when: ansible_os_family == "Debian"

  - name: "Remove config Docker options"
    file: path={{ item }} state=absent
    with_items: 
    - /var/lib/docker
    - /var/log/upstart/docker.log
    - /etc/default/docker
    when: ansible_os_family == "Debian"

  # CENTOS

  - name: stop Docker daemon
    service: name=docker state=stopped
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: uninstall Docker on CentOS7
    yum: name=docker-engine state=absent
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

