---
- name: removing Infrastructure Abstraction (Docker container) from the VM
  hosts: "{{ plat }}"
  become: true
  tasks:

  - name: Infrastructure Abstractor VIM Adaptor - removing Docker containers
    docker_container:
      name: son-sp-infrabstract
      state: absent

  - name: Infrastructure Abstractor WIM Adaptor - removing Docker containers
    docker_container:
      name: wim-adaptor
      state: absent

