---
- name: remove MongoDB container from the 'plat' machine
  hosts: "{{ plat }}"
  become: true
  tasks:
  - name: destroy mongo container
    docker_container:
      name: son-mongo
      state: absent

  - wait_for: host=0.0.0.0 port=27017 timeout=30 delay=10 state=drained
