---
- name: remove Docker containers from the SP VM
  hosts: "{{ plat }}"
  become: true
  tasks:

# Removing the Sonata MONITORY Docker Images

  - name: MONIT Probe - removing Docker containers
    docker_container:
      name: son-monitor-probe
      state: absent

  - name: MONIT MANAGER - removing Docker containers
    docker_container:
      name: son-monitor-manager
      state: absent

  - wait_for: host=0.0.0.0 port=8000 timeout=120 delay=10 state=drained

  - name: MONIT Push Gateway - removing Docker containers
    docker_container:
      name: son-monitor-pushgateway
      state: absent

  - wait_for: host=0.0.0.0 port=9091 timeout=120 delay=10 state=drained

  - name: MONIT PROMETHEUS - removing Docker containers
    docker_container:
      name: son-monitor-prometheus
      state: absent

  - wait_for: host=0.0.0.0 port=9090 timeout=120 delay=10 state=drained

  - name: MONIT MySQL - removing Docker containers
    docker_container:
      name: son-monitor-mysql
      state: absent

  - wait_for: host=0.0.0.0 port=3306 timeout=120 delay=10 state=drained

  - name: MONIT InfluxDB - removing Docker containers
    docker_container:
      name: son-monitor-influxdb
      image: tdierich/son-monitor-influxdb
      state: absent

  - wait_for: host=0.0.0.0 port=8086 timeout=120 delay=10 state=drained

