---
- name: remove MySQL container for MONITORY from the 'plat' machine
  hosts: "{{ plat }}"
  become: true
  tasks:
  - name: destroy mysql container
    docker_container:
      name: son-monitor-mysql
      state: absent

  - wait_for: host=0.0.0.0 port=3306 timeout=30 delay=10 state=drained
