---
- name: remove Docker containers REPOSITORIES from the SP VM appliance
  hosts: "{{ plat }}"
  become: true
  tasks:

# Removing the Sonata REPOs Docker Images

  - name: REPOs - stoping Docker containers
    docker_container:
      name: son-catalogue-repos
      state: absent

  - wait_for: host=0.0.0.0 port=4011 timeout=30 delay=10 state=drained
