# FW - set Iptables configuration

- name: install Python Firewall tools
  package: name=python-firewall state=present
  become: true

- yum: name=firewalld state=present
  become: true

- name: ensure the Firewall service is running
  service: name=firewalld state=started enabled=yes
  become: true

- name: open Squid port at firewall
  firewalld:
    port: 3128/tcp
    state: enabled
    immediate: true
    permanent: true
  notify: reload firewalld

- firewalld:
    service: http
    state: enabled
    immediate: true
    permanent: true
  notify: reload firewalld

- firewalld:
    service: https
    state: enabled
    immediate: true
    permanent: true
  notify: reload firewalld

### OPS
#
# sudo systemctl start firewalld.service
#
# firewall-cmd --state
#
###
