---
# tasks file for squid

- include: "{{ ansible_distribution_release }}.yml"

- name: installing SQUID proxy server
  package:
    name: squid
    state: latest

# preserve original config file
- fetch:
    src: /etc/squid/squid.conf
    dest: /tmp/squid.conf
    flat: yes
- copy:
    src: /tmp/squid.conf
    dest: /etc/squid/squid.conf.ORIG
    owner: root
    group: root
    mode: 0640

# register self-signed certificates
- file:
    path: /etc/squid/ssl
    state: directory
    mode: 0755
- copy:
    src: "{{ lookup('env','PWD') }}/roles/squid/files/cert.pem"
    dest: /etc/squid/ssl/cert.pem
    owner: root
    group: root
    mode: 0400
- copy:
    src: "{{ lookup('env','PWD') }}/roles/squid/files/key.pem"
    dest: /etc/squid/ssl/key.pem
    owner: root
    group: root
    mode: 0400


- name: setting your specific configuration
  copy:
    remote_src: false
    src: "{{ lookup('env','PWD') }}/roles/squid/files/squid.conf"
    dest: /etc/squid/squid.conf

- name: start SQUID service
  service: name=squid state=started enabled=yes

