# local package cache already up-to-date by 'common' role

- name: now, install SQUID on Ubuntu
  apt: name=squid3 state=present

# preserve original config file
- fetch:
    src: /etc/squid3/squid.conf
    dest: /tmp/squid.conf
    flat: yes
- copy:
    src: /tmp/squid.conf
    dest: /etc/squid3/squid.conf.ORIG
    owner: root
    group: root
    mode: 0640

- name: setting your specific configuration
  copy:
    remote_src: true
    src: "{{ role_path }}/files/squid.conf"
    dest: /etc/squid/squid.conf

- name: start SQUID service
  service: name=squid3 state=started enabled=yes

