---
heat_template_version: "2013-05-23"
resources:
  firewall-vnf:input:net:
    type: "OS::Neutron::Net"
    properties:
      name: "firewall-vnf:input:net"
  firewall-vnf:input:subnet:
    type: "OS::Neutron::Subnet"
    properties:
      cidr: "10.10.3.0/24"
      gateway_ip: "10.10.3.1"
      name: "firewall-vnf:input:subnet"
      network:
        get_resource: "firewall-vnf:input:net"
  firewall-vnf:output:net:
    type: "OS::Neutron::Net"
    properties:
      name: "firewall-vnf:output:net"
  firewall-vnf:output:subnet:
    type: "OS::Neutron::Subnet"
    properties:
      cidr: "10.10.4.0/24"
      gateway_ip: "10.10.4.1"
      name: "firewall-vnf:output:subnet"
      network:
        get_resource: "firewall-vnf:output:net"
  firewall-vnf:vdu01:
    type: "OS::Nova::Server"
    properties:
      flavor: "m1.small"
      image: "sonata_firewall_VM"
      name: "firewall-vnf:vdu01:a40d"
      networks:
      - port:
          get_resource: "firewall-vnf:vdu01:cp01"
      - port:
          get_resource: "firewall-vnf:vdu01:cp02"
      - port:
          get_resource: "firewall-vnf:vdu01:cp03"
  firewall-vnf:vdu01:cp01:
    type: "OS::Neutron::Port"
    properties:
      name: "firewall-vnf:vdu01:cp01"
      network:
        get_resource: "sonata-demo:mgmt:net"
  firewall-vnf:vdu01:cp02:
    type: "OS::Neutron::Port"
    properties:
      name: "firewall-vnf:vdu01:cp02"
      network:
        get_resource: "firewall-vnf:input:net"
  firewall-vnf:vdu01:cp03:
    type: "OS::Neutron::Port"
    properties:
      name: "firewall-vnf:vdu01:cp03"
      network:
        get_resource: "firewall-vnf:output:net"
  firewall-vnf:vnf:input:
    type: "OS::Neutron::RouterInterface"
    properties:
      router:
        get_resource: "iperf-2-firewall"
      subnet:
        get_resource: "firewall-vnf:input:subnet"
  firewall-vnf:vnf:output:
    type: "OS::Neutron::RouterInterface"
    properties:
      router:
        get_resource: "firewall-2-tcpdump"
      subnet:
        get_resource: "firewall-vnf:output:subnet"
  iperf-vnf:input:net:
    type: "OS::Neutron::Net"
    properties:
      name: "iperf-vnf:input:net"
  iperf-vnf:input:subnet:
    type: "OS::Neutron::Subnet"
    properties:
      cidr: "10.10.1.0/24"
      gateway_ip: "10.10.1.1"
      name: "iperf-vnf:input:subnet"
      network:
        get_resource: "iperf-vnf:input:net"
  iperf-vnf:output:net:
    type: "OS::Neutron::Net"
    properties:
      name: "iperf-vnf:output:net"
  iperf-vnf:output:subnet:
    type: "OS::Neutron::Subnet"
    properties:
      cidr: "10.10.2.0/24"
      gateway_ip: "10.10.2.1"
      name: "iperf-vnf:output:subnet"
      network:
        get_resource: "iperf-vnf:output:net"
  iperf-vnf:vdu01:
    type: "OS::Nova::Server"
    properties:
      flavor: "m1.small"
      image: "sonata_firewall_VM"
      name: "iperf-vnf:vdu01:6b4e"
      networks:
      - port:
          get_resource: "iperf-vnf:vdu01:cp01"
      - port:
          get_resource: "iperf-vnf:vdu01:cp02"
      - port:
          get_resource: "iperf-vnf:vdu01:cp03"
  iperf-vnf:vdu01:cp01:
    type: "OS::Neutron::Port"
    properties:
      name: "iperf-vnf:vdu01:cp01"
      network:
        get_resource: "sonata-demo:mgmt:net"
  iperf-vnf:vdu01:cp02:
    type: "OS::Neutron::Port"
    properties:
      name: "iperf-vnf:vdu01:cp02"
      network:
        get_resource: "iperf-vnf:input:net"
  iperf-vnf:vdu01:cp03:
    type: "OS::Neutron::Port"
    properties:
      name: "iperf-vnf:vdu01:cp03"
      network:
        get_resource: "iperf-vnf:output:net"
  iperf-vnf:vnf:output:
    type: "OS::Neutron::RouterInterface"
    properties:
      router:
        get_resource: "iperf-2-firewall"
      subnet:
        get_resource: "iperf-vnf:output:subnet"
  sonata-demo:firewall-2-tcpdump:
    type: "OS::Neutron::Router"
    properties:
      name: "sonata-demo:firewall-2-tcpdump"
  sonata-demo:iperf-2-firewall:
    type: "OS::Neutron::Router"
    properties:
      name: "sonata-demo:iperf-2-firewall"
  sonata-demo:mgmt:net:
    type: "OS::Neutron::Net"
    properties:
      name: "sonata-demo:mgmt:net"
  sonata-demo:mgmt:subnet:
    type: "OS::Neutron::Subnet"
    properties:
      cidr: "10.10.0.0/24"
      gateway_ip: "10.10.0.1"
      name: "sonata-demo:mgmt:subnet"
      network:
        get_resource: "sonata-demo:mgmt:net"
  tcpdump-vnf:input:net:
    type: "OS::Neutron::Net"
    properties:
      name: "tcpdump-vnf:input:net"
  tcpdump-vnf:input:subnet:
    type: "OS::Neutron::Subnet"
    properties:
      cidr: "10.10.5.0/24"
      gateway_ip: "10.10.5.1"
      name: "tcpdump-vnf:input:subnet"
      network:
        get_resource: "tcpdump-vnf:input:net"
  tcpdump-vnf:output:net:
    type: "OS::Neutron::Net"
    properties:
      name: "tcpdump-vnf:output:net"
  tcpdump-vnf:output:subnet:
    type: "OS::Neutron::Subnet"
    properties:
      cidr: "10.10.6.0/24"
      gateway_ip: "10.10.6.1"
      name: "tcpdump-vnf:output:subnet"
      network:
        get_resource: "tcpdump-vnf:output:net"
  tcpdump-vnf:vdu01:
    type: "OS::Nova::Server"
    properties:
      flavor: "m1.small"
      image: "sonata_firewall_VM"
      name: "tcpdump-vnf:vdu01:7972"
      networks:
      - port:
          get_resource: "tcpdump-vnf:vdu01:cp01"
      - port:
          get_resource: "tcpdump-vnf:vdu01:cp02"
      - port:
          get_resource: "tcpdump-vnf:vdu01:cp03"
  tcpdump-vnf:vdu01:cp01:
    type: "OS::Neutron::Port"
    properties:
      name: "tcpdump-vnf:vdu01:cp01"
      network:
        get_resource: "sonata-demo:mgmt:net"
  tcpdump-vnf:vdu01:cp02:
    type: "OS::Neutron::Port"
    properties:
      name: "tcpdump-vnf:vdu01:cp02"
      network:
        get_resource: "tcpdump-vnf:input:net"
  tcpdump-vnf:vdu01:cp03:
    type: "OS::Neutron::Port"
    properties:
      name: "tcpdump-vnf:vdu01:cp03"
      network:
        get_resource: "tcpdump-vnf:output:net"
  tcpdump-vnf:vnf:input:
    type: "OS::Neutron::RouterInterface"
    properties:
      router:
        get_resource: "firewall-2-tcpdump"
      subnet:
        get_resource: "tcpdump-vnf:input:subnet"
