---
- name: Upgrade the target machines (without rebooting)
  hosts: "{{ target }}"
  sudo: yes
  tasks: 

  - name:  upgrade all packages to the latest version
    yum: name='*' state=latest update_cache=yes
    when: ansible_os_family == "RedHat"

  - name: install APT dependencies
    apt: name={{ item }} state=present update_cache=yes
    with_items:
    - aptitude
    when: ansible_os_family == "Debian"

  - name:  upgrade all packages to the latest version
    apt: upgrade=yes update_cache=yes
    when: ansible_os_family == "Debian"

