---
# tasks file for docker-squid

- include_vars: "{{ lookup('env','PWD') }}/roles/docker-vpsa/defaults/main.yml"

- name: get Squid Docker image
  docker_image:
    #name: sameersbn/squid
    name: arocha/vpsa-squid-3.3.8 

- name: start Squid-proxy container
  docker_container:
    name: squid
    #image: sameersbn/squid
    image: arocha/vpsa-squid-3.3.8
    #env:
    state: started
    network_mode: bridge
    networks:
      - name: "{{ vl_enduser }}"
        aliases:
          - vpsa-enduser
      - name: "{{ vl_mgmt }}"
        aliases:
          - vpsa-mgmt
      #- name: "{{ vl_prx_addblk }}"
      #  aliases:
      #    - vpsa-prx-addblk
      #  links:
      #    - vpsa-squid-addblk:squid-addblk
      - name: "{{ vl_ids }}"
        aliases:
          - vpsa-ids
        links:
          - vpsa-ids
#      - name: "{{ vl_prx_ldap }}"
#        aliases:
#          - vpsa-prx-ldap
#        links:
#          - vpsa-prx-ldap:prx-ldap
    restart_policy: "unless-stopped"
    published_ports:
     - 3128:3128
     - 3129:3129
    volumes:
      - /var/log/sonata/squid:/var/log/squid
    log_driver: syslog # gelf

    #log_options:
    #  syslog-address: tcp://my-syslog-server:514
    #  syslog-facility: daemon

- wait_for: host=0.0.0.0 port=3128 timeout=30 delay=10 state=started

