
- name: create a new security group for SQUID-PROXY connections
  os_security_group:
    cloud: "os_{{ pop }}_{{ proj }}"
    state: present
    name: "{{ plat }}-secgrp"
    description: open ports for PROXY connections

- name: create a security rule on that group to allow PROXY connection
  os_security_group_rule:
    cloud: "os_{{ pop }}_{{ proj }}"
    security_group: "{{ plat }}-secgrp"
    protocol: tcp
    port_range_min: 3128
    port_range_max: 3128
    remote_ip_prefix: 0.0.0.0/0

