package:
  description: "SONATA vTC test service"
  maintainer: "Manuel Peuster, Paderborn University, manuel.peuster@uni-paderborn.de"
  name: sonata-vtc-service
  vendor: eu.sonata-nfv.package
  version: '0.4'
descriptor_extension: "yml"
version: '0.5'
