---
# tasks file for docker-openldap

- name: start OpenLDAP Docker container
  docker_container:

    name: openldap
    image: dinkel/openldap
    #env:
    state: started
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-mgmt
      - name: "{{ vl_proxy_ldap }}"
        aliases:
          - son-squid-ldap
    restart_policy: "unless-stopped"
    published_ports: 389:389
    volumes:
      - /var/log/sonata/openldap:/var/log/openldap

#- wait_for: host=0.0.0.0 port=389 timeout=30 delay=10 state=started

