- name:  upgrade all packages to the latest version
  yum: name='*' state=latest update_cache=yes

- name: DevTools group install
  yum: name="@Development tools" state=present

- name: install required libraries and tools for OVS
  yum: name={{ item }} state=latest
  with_items:
    - python-devel
    - python-pip
    - openssl-devel
    - libffi-devel
    - libtool
    - graphviz
    - Cython
    - iproute
    - kernel-devel
    - graphviz
    - kernel-debug-devel
    - autoconf
    - automake
    - rpm-build
    - redhat-rpm-config
    - python-twisted-core
    - python-zope-interface
    - PyQt4
    - desktop-file-utils
    - libcap-ng-devel
    - groff
    #- checkpolicy
    - selinux-policy-devel
    - wget
    - bridge-utils

- name: create a directory for RPM BUILD
  file:
    path: "{{ lookup('env','HOME') }}/rpmbuild/SOURCES"
    state: directory
    mode: 0755

- name: get openvswith LST tarball 
  get_url:
    url: http://openvswitch.org/releases/openvswitch-2.5.2.tar.gz
    #url: http://openvswitch.org/releases/openvswitch-2.7.0.tar.gz
    dest: "/tmp"

- name: unarchiving the tarball
  unarchive:
    src: "/tmp/openvswitch-2.5.2.tar.gz"
    dest: "{{ lookup('env','HOME') }}/rpmbuild/SOURCES"
    remote_src: True

- name: building OVS rpm
  shell: "rpmbuild -bb --nocheck {{ lookup('env','HOME') }}/rpmbuild/SOURCES/openvswitch-2.5.2/rhel/openvswitch-fedora.spec"

- name: install OVS server
  yum: name="{{ lookup('env','HOME') }}/rpmbuild/RPMS/x86_64/openvswitch-2.5.2-1.el7.centos.x86_64.rpm" state=present

- name: start OVS service
  service: name=openvswitch state=started enabled=true
