---
# tasks file for docker-openvpn

- name: start OpenVPN Server as a Docker container
  docker_container:
    name: vpnserver
    #image: kylemanna/openvpn
    image: lconceicao/vpnserver
    #env:
    state: started
    network_mode: bridge
    networks:

      - name: "{{ vl_mgmt }}"
        aliases:
          - vpsa-mgmt

      - name: "{{ vl_enduser }}"
        aliases:
          - vpsa-enduser

      - name: "{{ vl_fwin }}"
        aliases:
          - vpsa-vpn-fwin
        links:
          - vpsa-vpn-fwin:vpn-fwin

      - name: "{{ vl_fwout }}"
        aliases:
          - vpsa-vpn-fwout
        links:
          - vpsa-vpn-fwout:vpn-fwout

    restart_policy: "unless-stopped"
    volumes:
      - /var/log/sonata/openvpn:/var/log/openvpn
    log_driver: syslog # gelf

    #log_options:
    #  syslog-address: tcp://my-syslog-server:514
    #  syslog-facility: daemon

