---
# handlers file for Docker to RESTART
- pause:
    minutes: 1

- name: restart docker
  service: name=docker state=stopped

- name: restart docker
  service: name=docker state=started

- name: restart rsyslog
  service: name=rsyslog state=restarted

