---
- debug: msg="##### SP BSS DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

# Running the Sonata GK BSS Docker Image

- name: deploying GATEKEEPER BSS (as a Docker container)
  docker_container:
    name: son-bss
    image: "tdierich/son-yo-gen-bss"
    command: "grunt serve:integration --gkApiUrl=http://{{ fqdn }}/api/v2 --hostname=0.0.0.0 --userManagementEnabled=true --licenseManagementEnabled=true --debug"
    state: started
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-bss
    published_ports:
      - "25001:1337"
      - "25002:1338"
    restart_policy: "always"
