---

# talk to all hosts just so we can learn about them
- hosts: localhost
  connection: local
  tasks:
#    - include_vars: "~/.config/openstack/{{ vim }}{{ pop }}_{{ plat }}_vault.yaml"
#    - include_vars: vars/main.yml
#    - include_vars: "{{ item }}"
#      with_first_found:
#        - "vars/{{ ansible_distribution_release }}.yml"
#        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int }}.yml"
#        - "vars/{{ ansible_distribution }}.yml"
#        - "vars/{{ ansible_os_family }}.yml"
#      when: remote_user is not defined or distro is not defined

#    - name: terminate 'N' instances
#      os_server:
#        cloud: "{{ vim }}_{{ pop }}"
#        name: "{{ plat }}-{{ item.name }}"
#        state: "absent"
#      with_items: "{{ os_hosts.results }}"
#

  - name: Destroy instances
    os_server:
      name: "{{ hostvars[item].instance_name }}"
      state: absent
    with_items: "{{ groups['newnodes'] }}"

