---
- debug: msg="##### SP MONGODB DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

- name: deploy MongoDB as a Container (used by Monitory)
  docker_container:
    name: "son-mongo"
    image: "mongo"
    state: started
    restart_policy: "always"
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-mongo
          - mongo
    published_ports: 27017:27017

- wait_for: host=0.0.0.0 port=27017 timeout=30 delay=10 state=started
