---

- debug: msg="##### SP MONIT DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

# Running the Sonata MONITORY Docker Images

- include: monit/pushgw.yml
- include: monit/prometheus.yml
- include: monit/monitmgr.yml
- include: monit/probe.yml
