---
- debug: msg="##### SP PGSQL-MONITORING DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

- name: deploy a PostgreSQL database server as a Container
  docker_container:
    name: son-monitor-postgres
    image: ntboes/postgres-uuid
    env:
      #Defaults POSTGRES_DB=monitoring POSTGRES_USER=monitoringuser POSTGRES_PASSWORD=sonata
      POSTGRES_DB: "{{ mon_db_name }}"
      POSTGRES_USER: "{{ mon_db_user }}"
      POSTGRES_PASSWORD: "{{ mon_db_pass }}"
    state: started
    restart_policy: "always"
    command: postgres -p 5433
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-monitor-postgres
          - postgsql
    published_ports: 5433:5432
