---
- debug: msg="##### SP REPOs DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

- name: deploy REPOSITORIES as a Docker container (from the Registry to the SP VM appliance)
  docker_container:
    name: son-catalogue-repos
    image: "tdierich/son-catalogue-repos"
    state: started
    restart_policy: "always"
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-catalogue-repos
    dns_servers: "8.8.8.8"
    published_ports: "4002:4011"
