---
- name: deploy OpenLDAP server and libraries to the target machine
  hosts: "{{ target }}"
  become: true
  connection: local
  pre_tasks:
    - local_action: shell date +'%F %T'
      register: ts
    - debug:
        msg: "OpenLDAP deployment started @ {{ ts.stdout }}"
    - file:
        path: /var/log/ansible.log
        state: touch
        owner: "{{ lookup('env','USER') }}"
        group: "{{ lookup('env','USER') }}"
        mode: "u=rw,g=rw,o=rw"

  roles:
  - openldap

