---

- name: deploy a guest machine (VM)
  hosts: localhost
  become: false
  connection: local
  vars:
    localhome: "{{ lookup('env','PWD') }}" # needed for Jenkins CI 
  vars_files:
    - "{{ localhome }}/roles/{{ plat }}/vars/os_{{ pop }}_{{ proj }}_{{ distro }}.yml"
  pre_tasks:
    - local_action: shell date +'%F %T'
      register: ts
    - debug:
        msg: "{{ ts.stdout }}"
    - file:
        path: /var/log/ansible.log
        state: touch
        owner: "{{ lookup('env','USER') }}"
        group: "{{ lookup('env','USER') }}"
        mode: "u=rw,g=rw,o=rw"
    - debug:
        msg: "passing external variables: -e 'pop=alabs|ncsrd proj=qual|demo distro=trusty|xenial|Core'"
      become: true
  roles:
#    - { role: common, become: true }
#    - { role: openstackclients, become: true }
    - vm
