---

- name: connect to Openstack VIM and deploy a guest machine (VM)
  hosts: localhost
  become: false
  connection: local
#  vars_files:
#    - "{{ lookup('env','PWD') }}/roles/{{ plat | default(vm) }}/vars/os_{{ pop }}_{{ proj }}_{{ distro }}.yml"
  pre_tasks:
    - debug:
        msg: "EXTERNAL VARIABLES: -e 'plat=vm|sp|psa pop=alabs|ncsrd proj=qual|demo distro=trusty|xenial|Core nbofvms=N'"
    - debug: msg="{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
    - file:
        path: /var/log/ansible.log
        state: touch
        owner: "{{ lookup('env','USER') }}"
        group: "{{ lookup('env','USER') }}"
        mode: "u=rw,g=rw,o=rw"
      become: true
  roles:
    - { role: common, become: true }
    - { role: openstackclients, become: true }
    - vm

- include: "{{ lookup('env','PWD') }}/common.yml"
