default: &common_settings	
  host: localhost
  port: 5432
  pool: 40
  timeout: 5000


development:	
  <<: *common_settings
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: sonata
  username: postgres
	
  
test:
  <<: *common_settings
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: sonata_test
  username: postgres

integration:
  <<: *common_settings
  host: <%= ENV['DATABASE_HOST'] || 'postgres' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  database: <%= ENV['DATABASE_NAME'] || 'gatekeeper' %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'sonatatest' %>