- name: start 2 LDAP server containers
  docker_container:
    name: "ldap{{ item }}"
    recreate: yes
    image: dinkel/openldap # just for PoC - to retrieve private image
    command: sleep 1d
    volumes:
      - /var/log/sonata/ldap:/var/log/ldap
    log_driver: syslog # gelf
    #log_options:
    #  syslog-address: tcp://my-syslog-server:514
    #  syslog-facility: daemon
  with_sequence: count=2

