---
# tasks file for mysql
- name: install MySQL package on Redhat/CentOS machine
  yum: name={{ item }} state=present
  with_items:
  - mariadb
  - mariadb-server
  - MySQL-python
  - libselinux-python
  - libsemanage-python

- name: check for SElinux
  command: getenforce
  register: sestatus
  changed_when: false

- name: configure SElinux to enable DB listen on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: sestatus.rc != 0

- name: create the DB configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf owner=root group=root mode=0600
  notify: 
  - restart mariadb

- name: create target directory
  file: path=/var/lib/mysql state=directory owner=root group=root mode=0755

- name: start DB service/daemon on Redhat/CentOS machine
  service: name=mariadb state=started enabled=yes

- name: create the DB application
  mysql_db: name={{ dbname }} state=present

- name: create the DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
