---

#- file: path=/usr/local/pgsql/data state=directory owner=postgres group=postgres mode=0775
- file: path="/var/lib/postgresql/{{ tarball }}" state=directory mode=0777
- name: installing pgSQL APT GPG key
  apt_key: state=present url=https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: install pgSQL repo
  shell: sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'

- apt: update_cache=yes

- name: installing PostgreSQL
  apt: name={{ item }} update_cache=true state=latest
  with_items:
  - postgresql-{{ tarball }}
  - postgresql-contrib-{{ tarball }}
  - postgresql-client-{{ tarball }}
  - libpq-dev
  - python-psycopg2
  - firewalld
  tags: postgresql

- name: ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes sleep=5

# Managing firewall

- name: ensure the Firewall service is running
  service: name=firewalld state=started enabled=yes sleep=2

- name: open PostgreSQL port at firewall
  firewalld:
    port: 5432/tcp
    permanent: true
    state: enabled
    immediate: yes
  #when: not ( security_firewall is defined and not security_firewall )
  notify: reload firewalld

#- name: initialize database
#  become: yes
#  command: "/var/lib/postgresql/{{ tarball }}/bin/initdb -D /usr/local/pgsql/data"

