- name: create END USER (consumer) VLAN
  os_network:
    cloud: "os_{{ pop }}_{{ proj }}"
    state: present
    name: enduser
    shared: false
    external: false
  register: net_enduser

- os_subnet:
    cloud: "os_{{ pop }}_{{ proj }}"
    state: present
    network_name: "{{ net_enduser.id }}"
    name: subnet-enduser
    cidr: 172.23.0.0/24
    gateway_ip: 172.23.0.1
    enable_dhcp: true
    allocation_pool_start: 172.23.0.2
    allocation_pool_end: 172.23.0.126
    dns_nameservers:
       - 8.8.8.7
       - 8.8.8.8
    host_routes:
       #- destination: 0.0.0.0/0
       #  nexthop: 172.31.6.1
       - destination: 172.23.0.0/24
         nexthop: 172.23.0.1
  environment:
    OS_PROJECT_NAME: "son-{{ proj }}"
    OS_TENANT_NAME: "son-{{ proj }}"
    OS_TENANT_ID: ""

 
- name: create MGMT VLAN
  os_network:
    cloud: "os_{{ pop }}_{{ proj }}"
    state: present
    name: mgmt
    shared: false
    external: false
  register: net_mgmt

- os_subnet:
    cloud: "os_{{ pop }}_{{ proj }}"
    state: present
    network_name: "{{ net_mgmt.id }}"
    name: subnet-mgmt
    cidr: 172.23.1.0/24
    gateway_ip: 172.23.1.1
    enable_dhcp: true
    allocation_pool_start: 172.23.1.2
    allocation_pool_end: 172.23.1.126
    dns_nameservers:
       - 8.8.8.7
       - 8.8.8.8
    host_routes:
       #- destination: 0.0.0.0/0
       #  nexthop: 172.31.6.1
       - destination: 172.23.1.0/24
         nexthop: 172.23.1.1
  environment:
    OS_PROJECT_NAME: "son-{{ proj }}"
    OS_TENANT_NAME: "son-{{ proj }}"
    #OS_TENANT_ID: ""


- name: create LDAP authentication VLAN
  os_network:
    cloud: "os_{{ pop }}_{{ proj }}"
    state: present
    name: ldap
    shared: false
    external: false
  register: net_ldap

- os_subnet:
    cloud: "os_{{ pop }}_{{ proj }}"
    state: present
    network_name: "{{ net_ldap.id }}"
    name: subnet-ldap
    cidr: 172.23.2.0/24
    gateway_ip: 172.23.2.1
    enable_dhcp: true
    allocation_pool_start: 172.23.2.2
    allocation_pool_end: 172.23.2.126
    dns_nameservers:
       - 8.8.8.7
       - 8.8.8.8
    host_routes:
       #- destination: 0.0.0.0/0
       #  nexthop: 172.31.6.1
       - destination: 172.23.2.0/24
         nexthop: 172.23.2.1
  environment:
    OS_PROJECT_NAME: "son-{{ proj }}"
    OS_TENANT_NAME: "son-{{ proj }}"
    #OS_TENANT_ID: ""


- name: create PROXY-ADDBLOCK VLAN
  os_network:
    cloud: "os_{{ pop }}_{{ proj }}"
    state: present
    name: proxy-addblk
    shared: false
    external: false
  register: net_proxy_addblk

- os_subnet:
    cloud: "os_{{ pop }}_{{ proj }}"
    state: present
    network_name: "{{ net_proxy_addblk.id }}"
    name: subnet-proxy-addblk
    cidr: 172.23.3.0/24
    gateway_ip: 172.23.3.1
    enable_dhcp: true
    allocation_pool_start: 172.23.3.2
    allocation_pool_end: 172.23.3.126
    dns_nameservers:
       - 8.8.8.7
       - 8.8.8.8
    host_routes:
       #- destination: 0.0.0.0/0
       #  nexthop: 172.31.6.1
       - destination: 172.23.3.0/24
         nexthop: 172.23.3.1
  environment:
    OS_PROJECT_NAME: "son-{{ proj }}"
    OS_TENANT_NAME: "son-{{ proj }}"
    #OS_TENANT_ID: ""


- name: create PROXY-IDS VLAN
  os_network:
    cloud: "os_{{ pop }}_{{ proj }}"
    state: present
    name: proxy-ids
    shared: false
    external: false
  register: net_proxy_ids

- os_subnet:
    cloud: "os_{{ pop }}_{{ proj }}"
    state: present
    network_name: "{{ net_proxy_ids.id }}"
    name: subnet-proxy-ids
    cidr: 172.23.4.0/24
    gateway_ip: 172.23.4.1
    enable_dhcp: true
    allocation_pool_start: 172.23.4.2
    allocation_pool_end: 172.23.4.126
    dns_nameservers:
       - 8.8.8.7
       - 8.8.8.8
    host_routes:
       #- destination: 0.0.0.0/0
       #  nexthop: 172.31.6.1
       - destination: 172.23.4.0/24
         nexthop: 172.23.4.1
  environment:
    OS_PROJECT_NAME: "son-{{ proj }}"
    OS_TENANT_NAME: "son-{{ proj }}"
    #OS_TENANT_ID: ""

- name: create PROXY-FW VLAN
  os_network:
    cloud: "os_{{ pop }}_{{ proj }}"
    state: present
    name: proxy-fw
    shared: false
    external: false
  register: net_proxy_fw

- os_subnet:
    cloud: "os_{{ pop }}_{{ proj }}"
    state: present
    network_name: "{{ net_proxy_fw.id }}"
    name: subnet-proxy-fw
    cidr: 172.23.5.0/24
    gateway_ip: 172.23.5.1
    enable_dhcp: true
    allocation_pool_start: 172.23.5.2
    allocation_pool_end: 172.23.5.126
    dns_nameservers:
       - 8.8.8.7
       - 8.8.8.8
    host_routes:
       #- destination: 0.0.0.0/0
       #  nexthop: 172.31.6.1
       - destination: 172.23.5.0/24
         nexthop: 172.23.5.1
  environment:
    OS_PROJECT_NAME: "son-{{ proj }}"
    OS_TENANT_NAME: "son-{{ proj }}"
    #OS_TENANT_ID: ""

