---

- name: SONATA CMUD v2.1 - upgrade Operating System packages and useful tools
  hosts: "{{ plat }}"
  become: true
  connection: ssh
  vars_files:
    - "{{ lookup('env','PWD') }}/group_vars/os_{{ pop }}_{{ proj }}_{{ distro }}.yml"
  remote_user: "{{ vm_user }}"

  pre_tasks:
    - debug: msg="##### VM SW STANDARDIZATION STARTED {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

  roles:
     - common

