---
# Re-starting the Sonata GTK FUNCTIONS (Docker container)

- name: restarting GTK FUNCTIONS Docker container
  hosts: "{{ plat }}"
  become: true
  tasks:


  - name: GATEKEEPER FUNCTIONS - re-starting Docker container
    docker_container:
      name: son-gtkfnct
      image: sonatanfv/son-gtkfnct
      state: started
      restart: yes
      restart_policy: "unless-stopped"
      env:
        CATALOGUES_URL: http://{{ public_ip }}:4002/catalogues/api/v2
        RACK_ENV: integration
        #SECRET_KEY: son-install
      ports: "5500:5500"
      volumes:
        - /var/log/sonata/son-gtkfnct:/var/log/son-gtkfnct
      log_driver: syslog

  - wait_for: host=0.0.0.0 port=5500 timeout=120 delay=10 state=started
