---
- name: restarting GTK MANO Docker container
  hosts: "{{ plat }}"
  become: true
  tasks:


  # Re-starting GTK VIM (Docker container)

  - name: GATEKEEPER MANO
    docker_container:
      name: son-gtkmano
      image: sonatanfv/son-gtkmano
      state: started
      restart: yes
      restart_policy: "unless-stopped"
      env:
        RACK_ENV: integration
        MQSERVER: amqp://guest:guest@{{ public_ip }}:5672
        DATABASE_HOST: "{{ public_ip }}"
        DATABASE_PORT: 5432
        POSTGRES_PASSWORD: sonata
        POSTGRES_USER: sonatatest
        #SECRET_KEY: son-install
      links:
        - son-broker
        - son-postgres
      ports: "8001:8001"
      volumes:
        - /home/{{ ansible_user_id }}/son-gkeeper/son-gtkmano/:/opt/sonata/son-gktmano
        - /var/log/sonata:/var/log/son-gtkmano
      log_driver: syslog

  - wait_for: host=0.0.0.0 port=8001 timeout=30 delay=10 state=started

#  - name: wait for Container to finish
#    shell: >
#      docker wait son-gtkmano

