---
# Re-starting the Sonata GTK RECORDs (Docker container)

- name: restarting GTK REC Docker container
  hosts: "{{ plat }}"
  become: true
  tasks:

  - name: GATEKEEPER RECORDS - running Docker containers
    docker_container:
      name: son-gtkrec
      image: sonatanfv/son-gtkrec
      state: started
      restart: yes
      restart_policy: "unless-stopped"
      env:
        REPOSITORIES_URL: http://{{ public_ip }}:4002/records
        RACK_ENV: integration
        #SECRET_KEY: son-install
      ports: "5800:5800"
      volumes:
        - /var/log/sonata:/var/log/son-gtkrec
      log_driver: syslog

  - wait_for: host=0.0.0.0 port=5800 timeout=120 delay=10 state=started
