
# tasks file for docker

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_release }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- include_vars: "{{ lookup('env','PWD') }}/roles/{{ plat }}/defaults/main.yml"

- group:
    name: docker
    state: present

#- name: create a directory for Docker logging
#  file:
#    path: /var/log/docker
#    state: directory
#    owner: '{{ vm_user }}'
#    group: docker
#    mode: 0775
#  become: true

- include: "{{ ansible_distribution_release }}.yml"

