
- name: ensure that APT works with the HTTPS method, and that CA certificates are installed
  apt: name={{ item }} state=present update_cache=yes
  with_items:
  - apt-transport-https
  - ca-certificates

- name: Install Docker dependency libraries
  apt: name={{ item }} state=present update_cache=yes
  with_items:
  - apparmor
  - aptitude
  - python-apt
  - python3-apt
  - python-pip
  - python-dev
  - python-setuptools
  - python-httplib2
  - python-keyczar
  - python-pkg-resources
  - git

- name: "Install PIP"
  easy_install: name=pip

- name: "Install docker-py library on the remote server"
  pip: name={{ item }}  state=present
  with_items:
  - pycrypto>=2.6
  - six
  - requests
  - docker-py==1.9.0
  # "docker-compose 1.8.0 requires docker-py >1.9,<2.0, however if you're specifically setting docker-py to a version lower than 1.9.0 and installing docker-compose 1.8.0 it will upgrade docker-py all the way to 1.10.1 which presently breaks the string version comparison. Set docker-py to 1.9.0 prevent this."
  - urllib3
  - pyopenssl
  - ndg-httpsclient
  - pyasn1
  # “If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine or you can install the `urllib3`, `pyopenssl`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6”

#- name: on Trusty it is recommended to install the linux-image-extra kernel package
#  apt: name=linux-image-extra-$(uname -r) state=present update_cache=yes

- name: "Remove deprecated Docker package"
  apt: name=lxc-docker state=absent

- name: "Remove deprecated Docker APT repository"
  apt_repository: repo="deb https://get.docker.com/ubuntu docker main" state=absent update_cache=no

- name: "Remove deprecated Docker APT key"
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9
    state: absent

- name: "Install Docker APT key"
  apt_key:
    keyserver: p80.pool.sks-keyservers.net
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: "Install Docker APT repository in Ubuntu 14.04 LTS"
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
    state: present
  when: ansible_distribution_major_version == "14"

- name: update local package cache
  apt: update_cache=yes

- name: "Install Docker package"
  apt: name=docker-engine state=present

- name: "Ensure Docker is started at boot"
  service: name=docker enabled=yes

- name: "Add user to group"
  user: name=sonata shell=/bin/bash groups=docker append=yes

- name: "Configuring Docker Options"
  copy: src=docker2upstart dest=/etc/default/docker owner=root group=root mode=0644
#  notify:
#  - restart docker

- name: restart docker on Upstart (Ubuntu 14)
  service: name=docker state=restarted daemon_reload=yes
  when: ansible_distribution_release == "trusty"


# RSYSLOG

- apt: name=rsyslog state=latest

- service: name=rsyslog state=restarted enabled=yes

#- name: configure RSYSLOG
#  template:
#    src: rsyslog.j2
#    dest: /etc/rsyslog.d/30-docker.conf
#    owner: root
#    group: root
#    mode: 0644
#  notify:
#  - restart rsyslog

#- name: configure LOGROTATE
#  template:
#    src: logrotate.j2
#    dest: /etc/logrotate.d/docker
#    owner: root
#    group: root
#    mode: 0644
#  notify:
#  - restart rsyslog

