---
heat_template_version: "2015-04-30"
resources:
  firewall-vnf:input:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Net"
    properties:
      name: "firewall-vnf:input:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  firewall-vnf:input:subnet:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Subnet"
    properties:
      cidr: "192.168.131.0/24"
      gateway_ip: "192.168.131.1"
      name: "firewall-vnf:input:subnet:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      network:
        get_resource: "firewall-vnf:input:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  firewall-vnf:output:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Net"
    properties:
      name: "firewall-vnf:output:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  firewall-vnf:output:subnet:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Subnet"
    properties:
      cidr: "192.168.132.0/24"
      gateway_ip: "192.168.132.1"
      name: "firewall-vnf:output:subnet:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      network:
        get_resource: "firewall-vnf:output:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  firewall-vnf:vdu01:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Nova::Server"
    properties:
      flavor: "m1.small"
      image: "TestVM"
      name: "firewall-vnf:vdu01:dc48"
      networks:
      - port:
          get_resource: "firewall-vnf:vdu01:cp01:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      - port:
          get_resource: "firewall-vnf:vdu01:cp02:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      - port:
          get_resource: "firewall-vnf:vdu01:cp03:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  firewall-vnf:vdu01:cp01:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Port"
    properties:
      name: "firewall-vnf:vdu01:cp01:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      network:
        get_resource: "sonata-demo:mgmt:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  firewall-vnf:vdu01:cp02:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Port"
    properties:
      name: "firewall-vnf:vdu01:cp02:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      network:
        get_resource: "firewall-vnf:input:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  firewall-vnf:vdu01:cp03:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Port"
    properties:
      name: "firewall-vnf:vdu01:cp03:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      network:
        get_resource: "firewall-vnf:output:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  firewall-vnf:vnf:input:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::RouterInterface"
    properties:
      router:
        get_resource: "sonata-demo:iperf-2-firewall:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      subnet:
        get_resource: "firewall-vnf:input:subnet:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  firewall-vnf:vnf:output:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::RouterInterface"
    properties:
      router:
        get_resource: "sonata-demo:firewall-2-tcpdump:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      subnet:
        get_resource: "firewall-vnf:output:subnet:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  floating:firewall-vnf:vdu01:cp01:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::FloatingIP"
    properties:
      floating_network_id: "decd89e2-1681-427e-ac24-6e9f1abb1715"
      port_id:
        get_resource: "firewall-vnf:vdu01:cp01:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  floating:iperf-vnf:vdu01:cp01:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::FloatingIP"
    properties:
      floating_network_id: "decd89e2-1681-427e-ac24-6e9f1abb1715"
      port_id:
        get_resource: "iperf-vnf:vdu01:cp01:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  floating:tcpdump-vnf:vdu01:cp01:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::FloatingIP"
    properties:
      floating_network_id: "decd89e2-1681-427e-ac24-6e9f1abb1715"
      port_id:
        get_resource: "tcpdump-vnf:vdu01:cp01:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  iperf-vnf:input:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Net"
    properties:
      name: "iperf-vnf:input:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  iperf-vnf:input:subnet:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Subnet"
    properties:
      cidr: "192.168.129.0/24"
      gateway_ip: "192.168.129.1"
      name: "iperf-vnf:input:subnet:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      network:
        get_resource: "iperf-vnf:input:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  iperf-vnf:output:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Net"
    properties:
      name: "iperf-vnf:output:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  iperf-vnf:output:subnet:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Subnet"
    properties:
      cidr: "192.168.130.0/24"
      gateway_ip: "192.168.130.1"
      name: "iperf-vnf:output:subnet:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      network:
        get_resource: "iperf-vnf:output:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  iperf-vnf:vdu01:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Nova::Server"
    properties:
      flavor: "m1.small"
      image: "TestVM"
      name: "iperf-vnf:vdu01:4bac"
      networks:
      - port:
          get_resource: "iperf-vnf:vdu01:cp01:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      - port:
          get_resource: "iperf-vnf:vdu01:cp02:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      - port:
          get_resource: "iperf-vnf:vdu01:cp03:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  iperf-vnf:vdu01:cp01:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Port"
    properties:
      name: "iperf-vnf:vdu01:cp01:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      network:
        get_resource: "sonata-demo:mgmt:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  iperf-vnf:vdu01:cp02:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Port"
    properties:
      name: "iperf-vnf:vdu01:cp02:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      network:
        get_resource: "iperf-vnf:input:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  iperf-vnf:vdu01:cp03:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Port"
    properties:
      name: "iperf-vnf:vdu01:cp03:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      network:
        get_resource: "iperf-vnf:output:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  iperf-vnf:vnf:output:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::RouterInterface"
    properties:
      router:
        get_resource: "sonata-demo:iperf-2-firewall:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      subnet:
        get_resource: "iperf-vnf:output:subnet:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  sonata-demo:firewall-2-tcpdump:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Router"
    properties:
      name: "sonata-demo:firewall-2-tcpdump:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  sonata-demo:iperf-2-firewall:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Router"
    properties:
      name: "sonata-demo:iperf-2-firewall:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  sonata-demo:mgmt:internal:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::RouterInterface"
    properties:
      router: "20790da5-2dc1-4c7e-b9c3-a8d590517563"
      subnet:
        get_resource: "sonata-demo:mgmt:subnet:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  sonata-demo:mgmt:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Net"
    properties:
      name: "sonata-demo:mgmt:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  sonata-demo:mgmt:subnet:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Subnet"
    properties:
      cidr: "192.168.128.0/24"
      gateway_ip: "192.168.128.1"
      name: "sonata-demo:mgmt:subnet:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      network:
        get_resource: "sonata-demo:mgmt:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  tcpdump-vnf:input:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Net"
    properties:
      name: "tcpdump-vnf:input:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  tcpdump-vnf:input:subnet:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Subnet"
    properties:
      cidr: "192.168.133.0/24"
      gateway_ip: "192.168.133.1"
      name: "tcpdump-vnf:input:subnet:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      network:
        get_resource: "tcpdump-vnf:input:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  tcpdump-vnf:output:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Net"
    properties:
      name: "tcpdump-vnf:output:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  tcpdump-vnf:output:subnet:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Subnet"
    properties:
      cidr: "192.168.134.0/24"
      gateway_ip: "192.168.134.1"
      name: "tcpdump-vnf:output:subnet:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      network:
        get_resource: "tcpdump-vnf:output:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  tcpdump-vnf:vdu01:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Nova::Server"
    properties:
      flavor: "m1.small"
      image: "TestVM"
      name: "tcpdump-vnf:vdu01:bbe4"
      networks:
      - port:
          get_resource: "tcpdump-vnf:vdu01:cp01:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      - port:
          get_resource: "tcpdump-vnf:vdu01:cp02:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      - port:
          get_resource: "tcpdump-vnf:vdu01:cp03:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  tcpdump-vnf:vdu01:cp01:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Port"
    properties:
      name: "tcpdump-vnf:vdu01:cp01:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      network:
        get_resource: "sonata-demo:mgmt:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  tcpdump-vnf:vdu01:cp02:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Port"
    properties:
      name: "tcpdump-vnf:vdu01:cp02:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      network:
        get_resource: "tcpdump-vnf:input:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  tcpdump-vnf:vdu01:cp03:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::Port"
    properties:
      name: "tcpdump-vnf:vdu01:cp03:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      network:
        get_resource: "tcpdump-vnf:output:net:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
  tcpdump-vnf:vnf:input:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002:
    type: "OS::Neutron::RouterInterface"
    properties:
      router:
        get_resource: "sonata-demo:firewall-2-tcpdump:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"
      subnet:
        get_resource: "tcpdump-vnf:input:subnet:9df6a98f-9e11-4cb7-b3c0-b1375e7c0002"


