---

- name:  upgrade all packages to the latest version
  yum: name='*' state=latest update_cache=yes

- name: DevTools group install
  yum: name="@Development tools" state=present

- name: install required libraries and tools for PIP
  yum: name={{ item }} state=latest
  with_items:
    - python-devel
    - python-pip
    - openssl-devel
    - libffi-devel

# INSTALL VIA PIP - The packaged version might install older clients. If you want to make sure the latest clients are installed, you might need to install the clients with PIP.

- command: pip install --upgrade pip

- name: install required libraries for Shade (https://pypi.python.org/pypi/shade/)
  pip: name={{ item }} state=latest
  with_items:
    - requestsexceptions>=1.1.1
    - pbr>=0.11
    - netifaces>=0.10.4
    - munch
    - keystoneauth1>=2.11.0
    - jsonpatch
    - jmespath
    - ipaddress
    - dogpile.cache>=0.5.3
    - six

#- name: install os-client-config
#  pip: name=os-client-config state=present

- name: install Openstack command line clients
  pip: name={{ item }} state=latest
  with_items:
#    - openstack-nova-common
    - python-openstackclient
    - python-keystoneclient
    - python-heatclient
    - python-glanceclient
    - python-cinderclient
    - python-swiftclient
    - python-novaclient
    - python-neutronclient
    - python-designateclient
    #- python-ironicclient
    #- python-troveclient
    #- python-magnumclient

#- name: install RDO repos (provides RPM packages of Python Openstack command line clients)
#  yum: name=centos-release-openstack-{{ openstack_release }} state=present 

- name: get OpenStack Client Configuration Library (os-client-config)
  get_url:
    url: https://pypi.python.org/packages/27/13/aca5ca37a70ffefec4e6550b766c760743ccd68a7e0b9ebd1f801e7b178b/os-client-config-1.26.0.tar.gz#md5=0dd6b8d38e1375822fbff8e0df302631
    dest: "/tmp"

- name: install os-client-config
  pip: name='file:///tmp/os-client-config-1.26.0.tar.gz' state=present

- include: shade.yml

