
- name: get Shade (Python module needed by Ansible Cloud module)
  get_url:
    url: 'https://pypi.python.org/packages/8a/23/82202df7efe5bc0112f29700fa6907fc008f7fe0af8ac2e70860e31d7e51/shade-1.16.0.tar.gz#md5=a876208efd25dff182e534b261dfcd0a'
    #url: "https://pypi.python.org/packages/e4/a3/a2e95a990c0b96c9a20ad0504aeb191fa63c08a0b9a48bfdc68e82d49469/shade-1.21.0.tar.gz#md5=e504f186b511daf7eabfc3d5601c2038"
    dest: "/tmp"
#  register: new_archive

- name: install Shade
  pip: name='file:///tmp/shade-1.16.0.tar.gz' state=present
#  when: new_archive|changed

