---
# handlers file for Jenkins
- name: reload firewalld
  service: name=firewalld state=reloaded
  when: ansible_os_family == "RedHat"

- name: reload firewalld
  ufw: state=reloaded
  when: ansible_os_family == "Debian"

