swagger: "2.0"
info:
  title: "SONATA's SP API"
  description: "This is a proposal for the SONATA's SP API"
  version: "1.0.0"
host: sp.sonata-nfv.eu
schemes:
  - http
basePath: /api
produces:
  - application/json

paths:
  /:
    get:
      summary: nsr URL root
      description: Everything starts here.
      tags:
        - Root
      responses:
        '200':
          description: This list of paths.