---
development:
  sessions:
    default:
      database: son-catalogue-repository
      hosts:
      - mongo:27017
production:
  sessions:
    default:
      database: son-catalogue-repository
      hosts:
      - mongo:27017
test:
  sessions:
    default:
      database: son-catalogue-repository
      hosts:
      - mongo:27017
