---

- name: get ODL tarball
  get_url:
    url: https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/distribution-karaf/0.5.2-Boron-SR2/distribution-karaf-0.5.2-Boron-SR2.tar.gz
    dest: "/tmp"

- name: unarchiving ODL tarball
  unarchive:
    src: "/tmp/distribution-karaf-0.5.2-Boron-SR2.tar.gz"
    dest: "/tmp"
    remote_src: True

- name: install ODL
  shell: /tmp/distribution-karaf-0.5.2-Boron-SR2/bin/karaf
