---
- name: stopping RabbitMQ Docker container at SON-SP VM appliance
  hosts: "{{ plat }}"
  become: true
  tasks:

  - name: check if the DOCKER service exists
    stat: path=/etc/init.d/docker
    register: service_status

  - name: run the "SP Message Bus"
    docker_container: 
      name: son-broker
      state: stopped
    when: service_status.stat.exists

