---

- name: stopping MongDB database engine
  hosts: "{{ plat }}"
  become: true
  tasks:

  - name: stop MongoDB services
    docker_container:
      name: son-mongo
      state: stopped

  - wait_for: host=0.0.0.0 port=27017 timeout=30 delay=10 state=drained
