---
- name: stoping REPOSITORIES Docker containers at SP VM appliance
  hosts: "{{ plat }}"
  become: true
  tasks:

# Stopping the Sonata REPOs Docker Images

  - name: REPOs - stopping Docker containers
    docker_container:
      name: son-catalogue-repos
      state: stopped
  - wait_for: host=0.0.0.0 port=4011 timeout=30 delay=10 state=drained
