---

- name: deploying Infrastructure Abstractor VIM Adaptor (Docker container)
  docker_container:
    name: son-sp-infrabstract
    image: "tdierich/son-sp-infrabstract"
    restart_policy: "always"
    state: started
    env:
      broker_host: "son-broker"
      broker_uri: "amqp://guest:guest@son-broker:5672/%2F"
      repo_host: "son-postgres"
      repo_port: "5432"
      repo_user: "{{ ia_repo_user }}"
      repo_pass: "{{ ia_repo_pass }}"
      SONATA_SP_ADDRESS: "{{ fqdn }}"
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-sp-infrabstract
    volumes:
      - terraform_data:/root/terraform_data

