---
- name: destroy Apache from the 'target' machine'
  hosts: "{{ target }}"
  become: true
  tasks:

  - name: check if service is running
    stat: path=/etc/init.d/apache2
    register: service_status

  - name: stop Apache2 service
    service: name=apache2 state=stopped
    when: service_status.stat.exists
    register: service_stopped

  - name: remove Apache2 package
    apt: name=apache2 state=absent update_cache=yes

