---

- name: "destroy PostgreSQL from the VM appliance"
  hosts: "{{ target }}"
  become: true
  vars:
    tarball: "9.6"
  tasks:


# REDHAT/CENTOS
  - raw: /usr/bin/date >> /tmp/play.log
    when: ansible_os_family == "RedHat"

#  - name: check if service is running
##    stat: path=/usr/lib/systemd/system/postgresql-{{ tarball }}.service
#    command: systemctl status postgresql-{{ tarball }}
#    register: service_status
#    when: ansible_os_family == "RedHat" and ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

#  - debug: var=service_status

  - name: ensure the PostgreSQL service is stopped
    service: name=postgresql-{{ tarball }} state=stopped enabled=no
    register: service_stopped
    when: ansible_os_family == "RedHat"

  - name: removing pgSQL packages
    yum: name={{ item }} update_cache=true state=absent
    with_items:
    - postgresql96
    - postgresql96-libs
    - postgresql96-server
    - postgresql96-contrib
    - postgresql96-libs
    when: ansible_os_family == "RedHat" and ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

  - name: removing datafiles
    file: path={{ item }} state=absent
    with_items:
    - /var/run/postgresql/
    - /var/lib/pgsql/{{ tarball }}
    #- /var/log/pgsql/
    - /usr/lib64/pgsql
    - /usr/share/pgsql
    - /usr/pgsql-{{ tarball }}
    when: ansible_os_family == "RedHat"

  - raw: /usr/bin/date >> /tmp/play.log
    when: ansible_os_family == "RedHat"



# DEBIAN/UBUNTU

  - raw: /bin/date >> /tmp/play.log
    when: ansible_os_family == "Debian"

  - name: check if service is running
    stat: path=/etc/init.d/postgresql.dpkg-dist
    register: service_status
    when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"

  - name: ensure the PostgreSQL service is stopped
    service: name=postgresql state=stopped enabled=no
    register: service_stopped
    when: ansible_os_family == "Debian"

  - name: removing pgSQL packages
    apt: name={{ item }} update_cache=true state=absent
    with_items:
    - postgresql
    - postgresql-common
    - postgresql-client-common
    - postgresql-{{ tarball }}
    - postgresql-contrib-{{ tarball }}
    - libpq-dev
    - python-psycopg2
    when: ansible_os_family == "Debian"

  - name: removing datafiles
    file: path={{ item }} state=absent
    with_items:
    - /var/run/postgresql/
    - /var/lib/postgresql/
    - /var/log/postgresql/
    - /usr/lib/postgresql 
    - /etc/init.d/postgresql
    when: ansible_os_family == "Debian"

  - raw: /bin/date >> /tmp/play.log

