---
# tasks file for snort

- include: "{{ ansible_distribution_release }}.yml"

- name: Updating Snort Rule using Pulled Pork
  git: 
    repo: https://github.com/shirkdog/pulledpork.git
    dest: /tmp/pulledpork

- name: setup pulled pork
  copy:
    remote_src: true
    src: /tmp/pulledpork/pulledpork.pl
    dest: /usr/local/bin

- file:
    path: /usr/local/bin/pulledpork.pl
    owner: root
    group: root
    mode: 0755

- file:
    path: /etc/snort
    state: directory
    mode: 0755

- name: setup pulled pork
  copy:
    remote_src: true
    src: "{{ item }}"
    dest: /etc/snort
  with_fileglob:
    - /tmp/pulledpork/etc/*.conf

# provide feedback on the installed version
- command: sudo snort -V
  register: snort_ver
- debug:
    var: snort_ver.stdout

