---
- name: check if SSL Certificate is valid (https://www.ssllabs.com/ssltest/analyze.html)
  hosts: localhost
  connection: local
  become: false
  tasks:

  - name: test SSL 
    command: curl -i https://www.ssllabs.com/ssltest/analyze.html?d=sp.int.sonata-nfv.eu
    ignore_errors: yes
    changed_when: false
    register: ssl_cert_status

  - name: Report SSL Cert status
    fail:
      msg: |
        SSL Cert is not Ok.
        {{ ssl_cert_status.stdout }}
        {{ ssl_cert_status.stderr }}
    when: ssl_cert_status | failed
