---
- hosts: "{{ plat }}"
  become: true
  connection: ssh
  vars_files:
    - "{{ lookup('env','PWD') }}/group_vars/os_{{ pop }}_{{ proj }}_{{ distro }}.yml"
    - "{{ lookup('env','PWD') }}/group_vars/{{ plat }}/vault.yml"
  remote_user: "{{ vm_user }}"

  roles:
    - sp

