- name:  upgrade all packages to the latest version
  yum: name='*' state=latest update_cache=yes

- name: install LDAP server and tools
  yum: name={{ item }}
  with_items:
  - openldap
  - compat-openldap
  - openldap-clients
  - openldap-servers
  - openldap-servers-sql
  - openldap-devel

- name: start LDAP service
  service: name=slapd state=started enabled=yes


# GUIDE: http://www.itzgeek.com/how-tos/linux/centos-how-tos/step-step-openldap-server-configuration-centos-7-rhel-7.html
