---

- name: previous install APTitude
  apt: name=aptitude state=present

- name: upgrade all packages to the latest version
  apt: upgrade=yes update_cache=yes

- name: install LDAP server and tools
  apt: name={{ item }} state=present
  with_items:
  - slapd
  - ldap-utils
  - phpldapadmin

- name: install LDAP client
  apt: name={{ item }} state=present
  with_items:
  - libnss-ldap
  - libpam-ldap
  - nscd

# GUIDE: https://help.ubuntu.com/lts/serverguide/openldap-server.html
