---

- name: MANO Function Lifecycle Management Plugin (Docker container)
  docker_container:
    name: functionlifecyclemanagement
    image: "sonatanfv/functionlifecyclemanagement:{{ sp_ver }}"
    env:
      url_gk_api: "http://son-gtkapi:5000/api/v2/"
      url_nsr_repository: "http://son-catalogue-repos:4011/records/nsr/"
      url_vnfr_repository: "http://son-catalogue-repos:4011/records/vnfr/"
      url_monitoring_server: "http://son-monitor-manager:8000/api/v1/"
      broker_host: amqp://guest:guest@son-broker:5672/%2F
    restart_policy: "always"
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - functionlifecyclemanagement
    state: started
