version: '3.1'
services:
  humhub:
    build: .
    links:
      - "db:db"
    ports:
      - "8080:80"
    environment:
      HUMHUB_DB_USER: root
      HUMHUB_DB_PASSWORD: ${HUMHUB_DB_PASSWORD}
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${HUMHUB_DB_PASSWORD}
      MYSQL_DATABASE: humhub
