---

- name: starting Docker engine on the target VM appliance
  hosts: "{{ plat }}"
  become: true
  tasks:

  - name: check if the DOCKER service exists
    stat: path=/etc/init.d/docker
    register: service_status

  - name: start Docker services
    service: name=docker state=started 
    when: service_status != 0
