---

- name: starting PostgreSQL Docker container at SP VM appliance
  hosts: "{{ plat }}"
  become: true
  tasks:

  - name: starting PostgreSQL (Docker container)
    docker_container:
      name: son-postgres
      state: started

