---
- name: starting REPOSITORIES Docker containers at SP VM appliance
  hosts: "{{ plat }}"
  become: true
  tasks:

# Running the Sonata REPOs Docker Images

  - name: REPOs - running Docker containers
    docker_container:
      name: son-catalogue-repos
      state: started

