---
- hosts: "{{ plat }}"
  become: true
  connection: ssh
  pre_tasks:
    - debug: msg="{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
    - file:
        path: /var/log/ansible.log
        state: touch
        owner: "{{ lookup('env','USER') }}"
        group: "{{ lookup('env','USER') }}"
        mode: "u=rw,g=rw,o=rw"
      become: true
    - lineinfile:
        become: true
        path: "/etc/hosts"
        line: "{{ public_ip }} {{ plat_hostname }}"
        create: yes
        state: present

  roles:
    #- common
    - docker
    #- docker-haproxy
    - docker-snort
    #- docker-openldap
    - docker-squid
    #- docker-addblk
    #- docker-openvpn

  tasks:
    - include: "{{ lookup('env','PWD') }}/roles/{{ plat }}/tasks/vpsa-client.yml

