- name: Docker User Defined Network (vPSA MGMT)
  shell: "docker network create --driver=bridge \
--subnet=172.22.111.0/24 --gateway=172.22.111.1 \
--ip-range=172.22.111.128/25 '{{ vl_mgmt }}'"

- name: Docker User Defined Network (vPSA END USER)
  shell: "docker network create --driver=bridge \
--subnet=172.22.112.0/24 --gateway=172.22.112.1 \
--ip-range=172.22.112.128/25 '{{ vl_enduser }}'"

- name: Docker User Defined Network (vPORTAL)
  shell: "docker network create --driver=bridge \
--subnet=172.22.113.0/24 --gateway=172.22.113.1 \
--ip-range=172.22.113.128/25 '{{ vl_portal }}'"

- name: Docker User Defined Network (vVPN)
  shell: "docker network create --driver=bridge \
--subnet=172.22.114.0/24 --gateway=172.22.114.1 \
--ip-range=172.22.114.128/25 '{{ vl_vpn }}'"

- name: Docker User Defined Network (vPRX)
  shell: "docker network create --driver=bridge \
--subnet=172.22.115.0/24 --gateway=172.22.115.1 \
--ip-range=172.22.115.128/25 '{{ vl_prx }}'"

- name: Docker User Defined Network (vIDS)
  shell: "docker network create --driver=bridge \
--subnet=172.22.117.0/24 --gateway=172.22.117.1 \
--ip-range=172.22.117.128/25 '{{ vl_ids }}'"

- name: Docker User Defined Network (vFW INSIDE)
  shell: "docker network create --driver=bridge \
--subnet=172.22.118.0/24 --gateway=172.22.118.1 \
--ip-range=172.22.118.128/25 '{{ vl_fwin }}'"

- name: Docker User Defined Network (vFW OUTSIDE)
  shell: "docker network create --driver=bridge \
--subnet=172.22.119.0/24 --gateway=172.22.119.1 \
--ip-range=172.22.119.128/25 '{{ vl_fwout }}'"


