# CENTOS 7
- name: installing EPEL
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: installing JDK
  yum: name=java-1.8.0-openjdk state=present update_cache=yes

