#- name: create an internal NETWORK
#  os_network:
#    cloud: 'os_{{ pop }}_{{ proj }}'
#    state: present
#    name: int-net
#    shared: false
#    external: false
#  register: int_net

#- name: create a SUBNET for the internal network
#  os_subnet:
#    cloud: 'os_{{ pop }}_{{ proj }}'
#    state: present
#    network_name: '{{ int_net.id }}'
#    name: int-net-subnet
#    cidr: 192.168.10.0/24
#    gateway_ip: 192.168.10.1
#    enable_dhcp: true
#    allocation_pool_start: 192.168.10.100
#    allocation_pool_end: 192.168.10.200
#    dns_nameservers:
#       - 8.8.8.7
#       - 8.8.8.8
#    host_routes:
#       - destination: 0.0.0.0/0
#         nexthop: 192.168.10.1

#- name: create a ROUTER for the internal network
#  os_router:
#    cloud: 'os_{{ pop }}_admin'
#    state: present
#    name: int-net-router
#    network: demo-netw
#    external_fixed_ips:
#      - subnet: demo-subnet
#        #ip: 192.168.11.2
#    interfaces:
#      - int-net-subnet

- name: create MGMT network
  os_network:
    cloud: "os_{{ pop }}_{{ proj }}"
    state: present
    name: mgmt
    shared: false
    external: false
  register: net_mgmt

- name: create MGMT subnet
  os_subnet:
    cloud: "os_{{ pop }}_{{ proj }}"
    state: present
    network_name: "{{ net_mgmt.id }}"
    name: subnet-mgmt
    cidr: 172.22.1.0/24
    gateway_ip: 172.22.1.1
    enable_dhcp: true
    allocation_pool_start: 172.22.1.2
    allocation_pool_end: 172.22.1.126
    dns_nameservers:
       - 8.8.8.7
       - 8.8.8.8
    host_routes:
       - destination: 0.0.0.0/0
         nexthop: 172.22.1.1
