
- include_vars: "{{ lookup('env','PWD') }}/roles/{{ plat }}/vars/main.yml"

- include_vars: "{{ lookup('env','PWD') }}/group_vars/os_{{ pop }}_{{ proj }}_{{ distro }}.yml"

- name: launch a new Instance(s)
  vars:
    local_home: "{{ lookup('env','PWD') }}"
  os_server:
    # http://docs.openstack.org/developer/os-client-config/
    state: present
    cloud: "os_{{ pop }}_{{ proj }}"
    name: "{{ plat }}-{{ pop }}-{{ proj }}-{{ distro }}-{{ item }}-{{ ansible_date_time.epoch }}"
    image: "{{ image }}"
    key_name: "{{ key_name }}"
    flavor: "{{ flavor }}"
    availability_zone: "{{ availability_zone }}"
    security_groups:
      - "{{ os_security_groups }}"
    floating_ip_pools: "{{ fip }}"
    #auto_ip: yes
    nics:
      - net-id: "{{ int_net_id }}"
      #- net-id: "{{ ext_net_id }}"
    userdata: "{{ lookup('file', '{{ local_home }}/userdata/{{ distro }}.sh') }}"
    meta:
      hostname: "{{ plat }}-{{ pop }}-{{ proj }}-{{ distro }}-{{ item }}-{{ ansible_date_time.epoch }}"
      group: "{{ plat }}"
    timeout: 180
    wait: yes
  with_sequence: "start=1 end={{ nbofvms | default(1) }} format=%02x"
  register: "newvm"

- set_fact:
    public_ip: "'{{ item.openstack.accessIPv4 }}'"
  with_items: "{{ newvm.results }}"

- set_fact:
    plat_hostname: "{{ item.openstack.name }}"
  with_items: "{{ newvm.results }}"

