- name: install EPEL
  yum: name=epel-release state=present

- name: install required packages for Apache
  yum: name={{ item }} state=present
  with_items:
    - mod_ssl
    - python-certbot-apache

- name: install CertBot client
  yum: name=certbot state=present

- name: obtain Certificate
  shell: certbot certonly --webroot --email arocha@ptinovacao.pt -w /usr/share/nginx/html/ -d alabs.sonata-nfv.eu

- service: name=nginx state=stopped

- name: install Certificate
  shell: certbot install 
  notify: restart nginx

