---
plat: docker-vpsa
pop: alabs
proj: demo
distro: xenial

#vl_enduser: "{{ 'sonata.dem-net' if pop == 'ncsrd' and proj == 'dem' else 'demo-netw' }}"

vl_mgmt: vpsa-mgmt
vl_enduser: vpsa-enduser
vl_portal: vpsa-portal
vl_vpn: vpsa-vpn
vl_ids: vpsa-ids
vl_prx: vpsa-prx
vl_fwin: vpsa-fwin
vl_fwout: vpsa-fwout

