---
- name: restarting RabbitMQ Docker container on the SP VM appliance
  hosts: "{{ plat }}"
  become: true
  tasks:

  - name: check if the DOCKER service exists
    stat: path=/etc/init.d/docker
    register: service_status

  - name: restart RabbitMQ (SP Message Bus)
    docker_container: 
      name: son-broker
      image: rabbitmq
      state: started
      restart: yes
      restart_policy: unless-stopped
      env:
        RABBITMQ_CONSOLE_LOG: new
        #SECRET_KEY: son-install
      ports: 
        - "5672:5672"
        - "8080:15672"
      #privileged: yes

