---

- name: re-starting MongoDB database services
  hosts: "{{ plat }}"
  become: true
  tasks:

  - name: re-starting MongoDB
    docker_container:
      name: son-mongo
      state: started
      restart: yes
      restart_policy: unless-stopped

