---
# tasks file for firewall

# UBUNTU/DEBIAN

- name: start 'firewall' service
  service: name=ufw state=started
  when: ansible_os_family == "Debian"

- name: open SVC port at FW
  ufw:
    state: enabled
    rule: allow # TO FIX
  when: ansible_os_family == "Debian"
#
