version: "3.2"

services:
  rabbit:
    image: rabbitmq:3.6-management
    ports:
        - "15672:15672"
        
  mongo:
    image: mongo
    command: --smallfiles
    ports:
        - "27017:27017"
    # volumes:
        # - type: "volume"
          # source: "mongodb_data_volume"
          # target: "/data/db"
       
  translator:
    build:
      context: translator
    depends_on:
      - rabbit
      - mongo
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"

  splitter:
    build:
      context: splitter
    depends_on:
      - rabbit
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"        
        
  adaptor:
    build:
      context: adaptor
    depends_on:
      - rabbit
    ports:
        - "8001:8000"
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"

  mainengine:
    build:
      context: mainengine
    depends_on:
      - rabbit
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"

  gateway:
    build:
      context: gateway
    depends_on:
      - rabbit
    ports:
        - "8000:8000"
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
          
# volumes:
  # mongodb_data_volume:
        # external: true   