---

- debug: msg="##### SP GTK-FUNCTIONs DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

# Running the Sonata GK FUNCTIONS (Docker container)

- name: GATEKEEPER FUNCTIONS - running Docker containers
  docker_container:
    name: son-gtkfnct
    image: "sonatanfv/son-gtkfnct:{{ sp_ver }}"
    env:
      CATALOGUES_URL: http://son-catalogue-repos:4011/catalogues/api/v2
      RACK_ENV: integration
    state: started
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-gtkfnct
    published_ports: "5500:5500"
    restart_policy: "always"
