---
- debug: msg="##### SP GTK-KPI DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

- name: GATEKEEPER KEY PERFORMANCE INDICATORS (GTKKPI) (Docker container)
  docker_container:
    name: son-gtkkpi
    image: "sonatanfv/son-gtkkpi:{{ sp_ver }}"
    state: started
    restart_policy: "always"
    env:
      PUSHGATEWAY_HOST: "pushgateway"
      PUSHGATEWAY_PORT: 9091
      PROMETHEUS_PORT: 9090
      RACK_ENV: integration
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-gtkkpi
    published_ports: "5400:5400"
