---

- debug: msg="##### SP GTK-MANO DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

# Ensure son-gtkmano is not present
- name: DELETE GATEKEEPER MANO (GTKMANO) (Docker container)
  docker_container:
    name: son-gtkmano
    state: absent

# Populate pgSQL database MANO
- name: create data model and populate db
  shell: /usr/bin/docker run --net={{ docker_network_name }} -i -e DATABASE_HOST=son-postgres -e MQSERVER=amqp://guest:guest@son-broker:5672 -e RACK_ENV=integration -e DATABASE_PORT=5432 -e POSTGRES_PASSWORD={{ gtk_db_pass }} -e POSTGRES_USER={{ gtk_db_user }} -e POSTGRES_DB={{ gtk_db_name }} --rm=true sonatanfv/son-gtkmano:{{ sp_ver }} bundle exec rake db:migrate

# Start GTK MANO (Docker container)
- name: GATEKEEPER MANO
  docker_container:
    name: son-gtkmano
    image: "sonatanfv/son-gtkmano:{{ sp_ver }}"
    env:
      RACK_ENV: integration
      MQSERVER: amqp://guest:guest@son-broker:5672
      DATABASE_HOST: son-postgres
      DATABASE_PORT: 5432
      POSTGRES_PASSWORD: "{{ gtk_db_pass }}"
      POSTGRES_USER: "{{ gtk_db_user }}"
      POSTGRES_DB: "{{ gtk_db_name }}"
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-gtkmano
    state: started
    restart_policy: "always"
    published_ports: "5500:5500"
