---

- debug: msg="##### SP GTK-RATE-LIMITER DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

# Running the Sonata GK RATE LIMITER (Docker container)
- name: GATEKEEPER RATE LIMITER (GTKRLT) (Docker container)
  docker_container:
    name: son-gtkrlt
    image: "tdierich/son-gtkrlt"
    env:
      REDIS_URL=redis://son-redis:6379
    state: started
    restart_policy: "always"
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-gtkrlt
    exposed_ports: 5150
    published_ports: "5150:5150"
