---
# tasks file for haproxy

# http://cbonte.github.io/haproxy-dconv/

- name: installing HA Proxy
  include: "{{ ansible_os_family }}.yml"

- name: install HA Proxy
  package: name=haproxy state=present

- name: setting your specific configuration
  copy:
    remote_src: false
    src: "{{ lookup('env','PWD') }}/roles/haproxy/files/haproxy.cfg"
    dest: /etc/haproxy/haproxy.cfg

- name: start HA Proxy
  service: name=haproxy state=started enabled=yes

- command: haproxy -v
  become: true
  register: haproxy_ver
- debug:
    var: haproxy_ver.stdout

