---
# fils for Apache
- name: APACHE2 | installing Apache for CentOS
  include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: APACHE2 | installing Apache for Ubuntu
  include: debian.yml
  when: ansible_os_family == "Debian"

