# DEFAULT VM CONFIG
nbofvms: 1
vm_user: ubuntu
image: trusty-cldimg
flavor: m1.sp
os_security_groups: "{{ plat }}-secgrp"
fip: admin_floating_net
availability_zone: nova
region_name: RegionOne
key_name: son-install
#int_net_id: "f510b497-359e-427b-9156-3c6f6130b0d4" # PoPs
