# DEFAULT VM CONFIG
vm_user: centos
nbofvms: 1
image: ce7-cldimg
flavor: sp-flavor
os_security_groups: "{{ plat }}-secgrp"
fip: ext_net_id
availability_zone: nova
region_name: RegionOne
key_name: son-install

# DEMO-NET
#int_net_id: "ea7d9c50-5b1e-4968-804d-a6ec11c318c5" # sonata.dem-net
ext_net_id: "53d43a3e-8c86-48e6-b1cb-f1f2c48833de" # provider
